In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
arr1 = np.arange(0, 21, 1)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
arr2 = np.linspace(0, 20, num = 21, endpoint = True, retstep = False, dtype = int, axis = 0)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr4 = np.ones(10)
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr5 = np.empty(10)
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
#2.呈上題，將以上數列取出偶數。
arr1[2:21:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
#3.呈1題，將數列取出3的倍數。
arr1[3:21:3]

array([ 3,  6,  9, 12, 15, 18])